Repository wecode-bootcamp-korea/37-1st-WePleats-frontend, pull requests merged in 2022-09, with the labels that each got.

#2 [37기 장문정] ADD : Footer 레이아웃 완성
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/index.js
  src/styles/common.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#4 [37기 라용] ADD : 로그인 완료 (통신 테스트 완료)
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/styles/reset.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#1 [37기 라용] ADD : 리스트 페이지 완료
  .prettierrc
  public/data/data.json
  public/data/productInfo.json
  public/data/productItemInfo.json
  src/Router.js
  src/pages/ProductList/COLOR_CATE.js
  src/pages/ProductList/Card/Card.js
  src/pages/ProductList/Card/Card.scss
  src/pages/ProductList/Filter/Filter.js
  src/pages/ProductList/Filter/Filter.scss
  src/pages/ProductList/Product/Product.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청

#8 [37기 장문정] ADD : 제품 상세 & 리뷰 페이지 Merge 요청
  package.json
  public/data/product.json
  public/data/reviews.json
  public/images/brandImg.jpg
  src/components/Nav/Nav.scss
  src/pages/ProductList/Product/Product.js
  src/pages/ProductList/Product/Product.scss
  src/pages/ProductList/Product/components/Accordions/Accordion/Accordion.js
  src/pages/ProductList/Product/components/Accordions/Accordion/Accordion.scss
  src/pages/ProductList/Product/components/Accordions/Accordions.js
  src/pages/ProductList/Product/components/Accordions/Accordions.scss
  src/pages/ProductList/Product/components/Form/Form.js
  src/pages/ProductList/Product/components/Form/Form.scss
  src/pages/ProductList/Product/components/Modal/Modal.js
  src/pages/ProductList/Product/components/Modal/Modal.scss
  src/pages/ProductList/Product/components/Navigate/Navigate.js
  src/pages/ProductList/Product/components/Navigate/Navigate.scss
  src/pages/ProductList/Product/components/Review/Review.js
  src/pages/ProductList/Product/components/Review/Review.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청, 완료

#10 [37기 장문정] 상세페이지 Merge 재요청!
  public/data/reviews.json
  src/components/Nav/Nav.js
  src/pages/ProductList/Product/components/Modal/Modal.js
  src/pages/ProductList/Product/components/Review/Review.js
Labels: 멘토 리뷰 요청

#7 [37기 라용] ADD : 결제하기 레이아웃 완료, 추가 기능 구현
  public/data/orderList.json
  src/Router.js
  src/pages/Payment/OrderedItem.js
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
  src/pages/ProductList/ProductList.scss
  src/pages/SignUp/SignUp.scss
Labels: Conflict 해결 요청

#11 Modify : 상단 필터링 상수데이터 수정 완료
  src/pages/ProductList/COLOR_CATE.js
  src/pages/ProductList/Card/Card.js
Labels: 멘토 리뷰 요청
